version: '3.8'

services:

  php-fpm:
    build: 
      context: docker
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: 'php'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf